url: "https://thanbarbershop.github.io"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

encoding: UTF-8

exclude:
  - node_modules
  - script

sass:
  style: :compressed

theme: jekyll-theme-primer

github:
  private: false
  license:
    name: MIT
  source:
    branch: "main"
    path: "/"
  repository_url: "https://github.com/pages-themes/primer"
  
title: ThanBarberShop
description: Địa chỉ Cắt Tóc Nam Đẹp tại Hà Nội - Tiệm Cắt Tóc Nam Phong cách Barber tại Hà Nội - ThanBarberShop


# html minify
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: [html, head, body]
