url: "https://thanbarbershop.github.io"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - node_modules
  - script

sass:
  style: :compressed

theme: jekyll-theme-primer

github:
  private: false
  license:
    name: MIT
  source:
    branch: "main"
    path: "/"
  repository_url: "https://github.com/pages-themes/primer"
  

title: ThanBarberShop
description: Địa chỉ Cắt Tóc Nam Đẹp tại Hà Nội - ThanBarberShop
collections:
  blog:
    output: true
    permalink: /:collection/:categories:output_ext
