url: "https://thanbarbershop.github.io"
remote_theme: pages-themes/primer@v0.2.0
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  jekyll-remote-theme
google_analytics:
exclude:
  - node_modules
  - script

sass:
  style: :compressed

theme: jekyll-theme-primer

github:
  private: false
  license:
    name: MIT
  source:
    branch: "main"
    path: "/"
  repository_url: "https://github.com/pages-themes/primer"
  
title: ThanBarberShop
description: Địa chỉ Cắt Tóc Nam Đẹp tại Hà Nội - Tiệm Cắt Tóc Nam Phong cách Barber tại Hà Nội - ThanBarberShop
